---
# This is temporary; We will need to move to packages.yml
name: Build packages (M1)
on:
  - push

jobs:
  # This only uploads the arm64 wheels for Apple M1 Silicon usage
  build-macos-arm64:
    runs-on: macos-11.0
    name: "build-macos (3.8-3.10, arm64)"
    steps:
      - uses: actions/checkout@v2
      - name: Start postgresql service
        # This skips updating brew when installing a package
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
        run: |
          brew services start postgresql

      # This builds all possible Python versions (currently, 3.8 to 3.10)
      - uses: armenzg/cibuildwheel@main
        # Read about options here https://cibuildwheel.readthedocs.io/en/stable/options
        env:
          CIBW_ARCHS: arm64
          # XXX: temp: only one version to build
          CIBW_BUILD: cp39-macosx_arm64
          # It silences a warning since we can't test on Apple Silicon runners
          CIBW_TEST_SKIP: "*-macosx_arm64"
          # This allows substitution within setup.py
          PACKAGE_NAME: psycopg2-binary

      - run: |
          ls -l
          ls -l wheelhouse

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: packages_macos_arm64
          path: ./wheelhouse/*.whl

  build-macos:
    runs-on: macos-11.0

    steps:
      - name: Checkout repos
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Build packages
        run: ./scripts/build/build_macos.sh
        env:
          PACKAGE_NAME: psycopg2-binary
          PSYCOPG2_TESTDB: postgres
          PSYCOPG2_TEST_FAST: 1
          ARCHFLAGS: "-arch arm64"
          _PYTHON_HOST_PLATFORM: macosx-11.0-arm64

      - run: |
          ls -l
          ls -l wheels
          ls -l dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: packages_macos
          path: |
            dist/*/*${{ matrix.platform }}.whl
